# Generated by Django 4.1.4 on 2023-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображениe товара 400х400', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='mainapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужское'), ('Ж', 'Женское'), ('У', 'Унисекс')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shirt_slogan',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткое описание'),
        ),
    ]
