# Generated by Django 4.1.4 on 2023-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужское'), ('Ж', 'Женское'), ('У', 'Унисекс')], max_length=1, verbose_name='Пол'),
        ),
    ]
