# Generated by Django 4.1.4 on 2022-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
