# Generated by Django 4.1.4 on 2023-02-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('hot', 'hot')], max_length=3, verbose_name='Наклейка'),
        ),
    ]
