# Generated by Django 4.1.4 on 2023-04-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_size_label_shoes_alter_size_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='head_image',
            field=models.ImageField(blank=True, default='cat_head_image_default.jpeg', help_text='Размер 1350х550', upload_to='categories', verbose_name='Изображение в заголовке при выборе категории'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, help_text='600x400', null=True, upload_to='tags'),
        ),
    ]
