# Generated by Django 4.1.4 on 2023-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_tag_head_image_alter_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
