# Generated by Django 4.1.4 on 2023-04-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tag_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег товаров', 'verbose_name_plural': 'Теги товаров'},
        ),
    ]
