# Generated by Django 4.1.4 on 2023-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_mainbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='tag',
            name='head_image',
            field=models.ImageField(blank=True, default='defaults/category/cat_head_image_default.jpeg', help_text='Размер 1350х550', upload_to='categories', verbose_name='Изображение в заголовке при выборе категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='mainapp.category'),
        ),
    ]
