# Generated by Django 4.1.4 on 2023-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_product_category_alter_tag_head_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header_show',
            field=models.BooleanField(default=True, verbose_name='Показывать на хедере'),
        ),
    ]
