# Generated by Django 4.1.4 on 2023-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_category_header_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_pos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Позиция в хедере'),
        ),
    ]
