# Generated by Django 4.1.4 on 2023-04-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_category_order_pos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_pos', '-name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
