# Generated by Django 4.1.4 on 2023-02-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название новости')),
                ('trailer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Анонс статьи')),
                ('author_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Автор')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumb_image', models.ImageField(blank=True, default='defaults/news/default400-266.png', help_text='Изображение на главной странице 400x266', null=True, upload_to='news')),
                ('body_image', models.ImageField(blank=True, help_text='Изображение в новости 900х450', null=True, upload_to='news')),
                ('body', models.TextField(help_text='Для форматирования можно использовать html теги', verbose_name='Сама новость')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='newsapp.newscategory', verbose_name='Категория')),
                ('tags', models.ManyToManyField(related_name='news', to='newsapp.newstag')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
