# Generated by Django 4.1.4 on 2023-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body_image',
            field=models.ImageField(blank=True, default='defaults/news/default_main.png', help_text='Изображение в новости 900х450', null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='newsapp.newstag'),
        ),
    ]
